[package]
name = "rust-vips"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.8.1"
infer = "0.19.0"
libvips = "1.7.0"
reqwest = { version = "0.12.12", features = ["blocking"]}
serde = { version = "1.0.217", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
